import 'package:get/get.dart';

class StringTranslations extends Translations {
  @override
  // TODO: implement keys
  Map<String, Map<String, String>> get keys => {
        'ru_RU': {
          'mainPage': 'Главная',
          'favorite': 'Избранное',
          'create': 'Создать',
          'message': 'Сообщения',
          'profile': 'Профиль',
          'category': 'Категории',
          'whatYouAreLookingFor': 'Что вы ищете?',
          'weFound': 'Мы нашли',
          'advertisement': 'объявлений',
          'sorting': 'Сортировка',
          'filter': 'Фильтры',
          'expensive': 'Дорогие',
          'cheap': 'Дешевые',
          'new': 'Новые',
          'location': 'Местоположение',
          'choose': 'Выбрать',
          'price': 'Цена',
          'exchange': 'Обмен',
          'free': 'Бесплатно',
          'from': 'От',
          'to': 'До',
          'welcomeToIzle': 'Добро пожаловать на izle',
          'enter': 'Войти',
          'phone': 'Телефон',
          'yourPassword': 'Ваш пароль',
          'show': 'показать',
          'forgetPassword': 'Забыли пароль?',
          'youAgreeWithRule':
              'При входе вы соглашаетесь с нашими Условиями использования.',
          'iAgreeWithRule':
              'Я соглашаюсь с правилами использования сервиса, а также с передачей и обработкой моих данных в izle. Я подтверждаю свое совершеннолетие и ответственность за размещение объявления.',
          'profileAndSetting': 'Профиль и настройки',
          'settings': 'Настройки',
          'policeConfindential': 'Политика конфиденциальности',
          'aboutApp': 'О приложении',
          'createAd': 'Создать объявления',
          'addPhoto': 'Добавить фото',
          'headlineTitle': 'Заголовок объявления*',
          'exampleSkil': 'Например: Велосипед SKIL2 MAX',
          'desctiption': 'Описание',
          'desctiptionShouldNotBe': 'Описание должно быть не короче 10 знаков',
          'contact': 'Контактное лицо',
          'preview': 'Предпросмотр',
          'publish': 'Опубликовать',
          'complain': 'Пожаловаться',
          'allAdsAuthor': 'Все объявления автора',
          'similarAds': 'Похожие объявления',
          'call': 'Позвонить',
          'whatIsWrongWithAd': 'Что не так с объявлением?',
          'chooseMessage': 'Выберите сообщения',
          'recent': 'Недавные',
          'important': 'Важные',
          'archive': 'Архивные',
          'unreaded': 'Непрочитанные',
          'toBlock': 'Заблокировать',
          'toArchive': 'Архивировать',
          'toMakeImporant': 'Пометить как важное',
          'delete': 'Удалить',
          'buyPackage': 'Купить пакет',
          'active': 'Активные',
          'inActive': 'Неактивные',
          'yourWallet': 'Ваш кошелек',
          'paymentHistory': 'История платежей',
          'settingsAndOther': 'Настройки и другое',
          'help': 'Помощь',
          'conditionUsage': 'Условия использования',
          'edit': 'Редактировать',
          'logOut': 'Выйти',
          'toAdvertise': 'Рекламировать',
          'raiseBy300Sum': 'Поднять на 300 сум',
          'yourBalance': 'Ваш баланс',
          'walletIsUsed':
              'Кошелек используется для оплаты всех платных услуг izle (реклама, размещение объявлений и покупка пакетов).',
          'topUpBalance': 'Пополнить баланс',
          'chooseSum': 'Выберите сумму пополнения',
          'priceIsWithTaxs': 'Цены указаны со всеми налогами',
          'editProfile': 'Редактировать профиль',
          'notification': 'Уведомления',
          'yourResume': 'Ваше резюме',
          'yourName': 'Ваше имя',
          'actualResume': 'Актуальное резуме',
          'wantToUpdateResume':
              'Хотите обновить резюме? Удалить и загрузите новое.',
        },
      };
}
